server {
    listen 80;
    server_name localhost;

    location /storage/ {
        alias /var/www/backend/storage/app/public/;
    }

    location ~ ^/(api|sanctum|_debugbar) {
        root /var/www/html/public;
        fastcgi_pass laravel-api:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
    }

    location / {
        proxy_pass http://react-app-dev:5173;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
